/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagelib;

import imagelib.components.ImageView;
import imagelib.image_lab.tools.ImageTools;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;

/**
 *
 * @author Pablo
 */
public class PreviewImage extends JFrame {

    private BufferedImage inImage, outImage;
    float hue = 0;
    float saturation = 0;
    float light = 0;
    /**
     * Creates new form Preview
     */
    public PreviewImage(BufferedImage image) {
        initComponents();
        this.setTitle("Preview");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(600, 700);
        
        inImage = image;
        outImage = image;
        imageView1.setImage(outImage);
        imageView1.setScaleType(ImageView.FIT_XY);
        this.setVisible(true);
    }
    
    private void updateImage(){
        outImage = ImageTools.adjustHSL(inImage, hue, saturation, light);
        imageView1.setImage(outImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageView1 = new imagelib.components.ImageView();
        jPanel1 = new javax.swing.JPanel();
        slHue = new javax.swing.JSlider();
        slSaturation = new javax.swing.JSlider();
        slBright = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout imageView1Layout = new javax.swing.GroupLayout(imageView1);
        imageView1.setLayout(imageView1Layout);
        imageView1Layout.setHorizontalGroup(
            imageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        imageView1Layout.setVerticalGroup(
            imageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(imageView1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        slHue.setValue(0);
        slHue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slHueStateChanged(evt);
            }
        });
        jPanel1.add(slHue);

        slSaturation.setValue(0);
        slSaturation.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slSaturationStateChanged(evt);
            }
        });
        jPanel1.add(slSaturation);

        slBright.setValue(0);
        slBright.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slBrightStateChanged(evt);
            }
        });
        jPanel1.add(slBright);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slHueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slHueStateChanged
        hue = (float) slHue.getValue() / 100f;
        System.out.println("Hue: " + hue);
        updateImage();
    }//GEN-LAST:event_slHueStateChanged

    private void slSaturationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slSaturationStateChanged
        saturation = (float) slSaturation.getValue() / 100f;
        System.out.println("Saturation: " + saturation);
        updateImage();
    }//GEN-LAST:event_slSaturationStateChanged

    private void slBrightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slBrightStateChanged
        light = (float) slBright.getValue() / 100f;
        System.out.println("Light: " + light);
        updateImage();
    }//GEN-LAST:event_slBrightStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imagelib.components.ImageView imageView1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider slBright;
    private javax.swing.JSlider slHue;
    private javax.swing.JSlider slSaturation;
    // End of variables declaration//GEN-END:variables
}
